import assert from 'node:assert/strict'

const packageSpecifier = ['@nerima-games', 'mc-physics'].join('/')
const physics = await import(packageSpecifier)

const expectedExports = [
  'ARROW_PROFILE',
  'CACTUS_SHAPE',
  'COLLISION_SHAPE_AABBS',
  'CONTACT_EPSILON',
  'CentreY',
  'DEFAULT_ENTITY_COLLISION_OPTIONS',
  'DEFAULT_EXPLOSION_LIMITS',
  'DEFAULT_GLIDE_CONFIG',
  'DEFAULT_TNT_FUSE_SECS',
  'DeltaTimeSecs',
  'EGG_PROFILE',
  'FIRST_FRAME_DELTA_SECS',
  'FULL_BLOCK_SHAPE',
  'FootY',
  'GLIDE_CLIMB_CONVERSION_PER_SECOND',
  'GLIDE_CLIMB_LIFT_MULTIPLIER',
  'GLIDE_DIVE_CONVERSION_PER_SECOND',
  'GLIDE_GRAVITY_PER_SECOND_SQUARED',
  'GLIDE_HORIZONTAL_DRAG_PER_SECOND',
  'GLIDE_LIFT_CANCEL_FACTOR',
  'GLIDE_TURN_RATE_PER_SECOND',
  'GLIDE_VERTICAL_DRAG_PER_SECOND',
  'GRAVITY_Y',
  'HalfHeight',
  'MAX_DELTA_SECS',
  'MAX_TNT_FUSE_ADVANCE_SECS',
  'MIN_DELTA_SECS',
  'PLAYER_HALF_HEIGHT',
  'PLAYER_HALF_WIDTH',
  'PRESSURE_PLATE_SHAPE',
  'SLAB_SHAPE',
  'SNOWBALL_PROFILE',
  'TERMINAL_VELOCITY_Y',
  'TRIDENT_PROFILE',
  'aabbOfCollisionShape',
  'aabbsOfBlockShape',
  'advanceFallTracking',
  'applyExplosionPlan',
  'applyFluidMotion',
  'applyKnockback',
  'applyMovementInput',
  'applyPrimedTntPlan',
  'applySurfaceMotion',
  'blockAABB',
  'blockAtFromKernel',
  'blockEnvironmentFromKernel',
  'blockPropertiesAtFromKernel',
  'centreOfFoot',
  'clampDeltaTime',
  'clampSneakEdge',
  'collidesWith',
  'createFallTrackingState',
  'deltaTimeBetween',
  'detectEntityCollisions',
  'entityAABB',
  'fallingBlockCandidateAt',
  'footOfCentre',
  'glideStep',
  'integrate',
  'integrateBody',
  'intersects',
  'isClampedDelta',
  'isRestingOn',
  'launchProjectile',
  'maxFallPerStep',
  'maxSpeedWithoutTunnelling',
  'penetrationY',
  'pistonExtrusion',
  'planExplosion',
  'planPrimedTnt',
  'position',
  'primeTnt',
  'resetFallTrackingState',
  'resolveBody',
  'resolveEntityCollisions',
  'resolveOptionsFromKernel',
  'resolveWorld',
  'sampleBlockHazards',
  'sampleFluidEffects',
  'sampleSurfaceEffects',
  'standingPlaneAbove',
  'stepBody',
  'stepProjectile',
  'stepWorld',
  'voxelRaycast',
]

assert.deepEqual(Object.keys(physics).sort(), expectedExports)
assert.equal(physics.DeltaTimeSecs(0), 0)
assert.equal(physics.FULL_BLOCK_SHAPE.minX, 0)
assert.equal(typeof physics.voxelRaycast, 'function')
assert.equal(typeof physics.planExplosion, 'function')

process.stdout.write(`package smoke passed: ${expectedExports.length} exports\n`)
